name: Build MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Set permission for build bash file
      run: chmod +x ./build_gio.sh

    - name: Install gogio tool
      run: go install github.com/g45t345rt/gio-cmd/gogio@latest

    - name: Build macos amd64
      run: ./build_gio.sh macos amd64

    - name: Build macos arm64
      run: ./build_gio.sh macos arm64

    - name: Zip app
      run: |
        cd ./build
        zip -r g45w_macos_amd64.zip g45w_macos_amd64.app
        zip -r g45w_macos_arm64.zip g45w_macos_arm64.app
        rm -r g45w_macos_amd64.app g45w_macos_arm64.app
      
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: Build MacOS
        path: build