name: Build IOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.10

    - name: Set permission for build bash file
      run: chmod +x ./build_gio.sh

    - name: Install gogio tool
      run: go install github.com/g45t345rt/gio-cmd/gogio@latest

    - name: Build ios arm64
      run: ./build_gio.sh ios arm64

    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: Build IOS
        path: build