name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Install gogio tool
      run: go install github.com/g45t345rt/gio-cmd/gogio@latest

    - name: Build windows amd64
      run: bash build_gio.sh windows amd64

    - name: Build windows arm64
      run: bash build_gio.sh windows arm64

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: Build Windows
        path: build